-- CreateTable
CREATE TABLE `Menus` (
    `id_menu` INTEGER NOT NULL AUTO_INCREMENT,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `name` VARCHAR(200) NOT NULL,
    `price` VARCHAR(200) NOT NULL,
    `image` VARCHAR(200) NOT NULL,

    PRIMARY KEY (`id_menu`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
